import { IconType } from "react-icons";

import {
  HiArrowUpRight,
  HiOutlineLink,
  HiArrowTopRightOnSquare,
  HiEnvelope,
  HiCalendarDays,
  HiArrowRight,
  HiOutlineEye,
  HiOutlineEyeSlash,
  HiOutlineDocument,
  HiOutlineGlobeAsiaAustralia,
  HiOutlineRocketLaunch,
  HiOutlineTrophy,
  HiOutlinePhone,
  HiOutlineMapPin,
  HiOutlineClipboardDocument,
  HiOutlineCheck,
} from "react-icons/hi2";

import {
  PiHouseDuotone,
  PiUserCircleDuotone,
  PiGridFourDuotone,
  PiBookBookmarkDuotone,
  PiImageDuotone,
  PiStarDuotone,
  PiChatCircleDuotone,
  PiCpuDuotone,
  PiBrainDuotone,
  PiCodeDuotone,
} from "react-icons/pi";

import {
  SiJavascript,
  SiNextdotjs,
  SiFigma,
  SiSupabase,
  SiPython,
  SiReact,
  SiTensorflow,
  SiHuggingface,
  SiDocker,
  SiGit,
  SiPostgresql,
  SiFastapi,
  SiLangchain,
  SiAnthropic,
  SiScikitlearn,
  SiPandas,
  SiNumpy,
  SiFlask,
  SiStreamlit,
  SiPytorch,
  SiKeras,
  SiOpencv,
  SiMysql,
  SiMongodb,
  SiPostman,
} from "react-icons/si";

import { FaDiscord, FaGithub, FaLinkedin, FaX, FaThreads, FaInstagram, FaXTwitter, FaFacebook, FaPinterest, FaWhatsapp, FaReddit, FaTelegram, } from "react-icons/fa6";

export const iconLibrary: Record<string, IconType> = {
  arrowUpRight: HiArrowUpRight,
  copy: HiOutlineClipboardDocument,
  check: HiOutlineCheck,
  arrowRight: HiArrowRight,
  email: HiEnvelope,
  globe: HiOutlineGlobeAsiaAustralia,
  person: PiUserCircleDuotone,
  grid: PiGridFourDuotone,
  book: PiBookBookmarkDuotone,
  openLink: HiOutlineLink,
  calendar: HiCalendarDays,
  home: PiHouseDuotone,
  gallery: PiImageDuotone,
  trophy: HiOutlineTrophy,
  phone: HiOutlinePhone,
  mapPin: HiOutlineMapPin,
  star: PiStarDuotone,
  chat: PiChatCircleDuotone,
  cpu: PiCpuDuotone,
  brain: PiBrainDuotone,
  code: PiCodeDuotone,
  discord: FaDiscord,
  eye: HiOutlineEye,
  eyeOff: HiOutlineEyeSlash,
  github: FaGithub,
  linkedin: FaLinkedin,
  x: FaX,
  twitter: FaXTwitter,
  threads: FaThreads,
  arrowUpRightFromSquare: HiArrowTopRightOnSquare,
  document: HiOutlineDocument,
  rocket: HiOutlineRocketLaunch,
  javascript: SiJavascript,
  nextjs: SiNextdotjs,
  supabase: SiSupabase,
  figma: SiFigma,
  facebook: FaFacebook,
  pinterest: FaPinterest,
  whatsapp: FaWhatsapp,
  reddit: FaReddit,
  telegram: FaTelegram,
  instagram: FaInstagram,
  python: SiPython,
  react: SiReact,
  tensorflow: SiTensorflow,
  huggingface: SiHuggingface,
  docker: SiDocker,
  git: SiGit,
  postgresql: SiPostgresql,
  fastapi: SiFastapi,
  langchain: SiLangchain,
  anthropic: SiAnthropic,
  scikitlearn: SiScikitlearn,
  pandas: SiPandas,
  numpy: SiNumpy,
  flask: SiFlask,
  streamlit: SiStreamlit,
  pytorch: SiPytorch,
  keras: SiKeras,
  opencv: SiOpencv,
  mysql: SiMysql,
  mongodb: SiMongodb,
  postman: SiPostman,
};

export type IconLibrary = typeof iconLibrary;
export type IconName = keyof IconLibrary;